Repository GTcreyon/SM63Redux, pull requests merged in 2023-03, with the labels that each got.

#75 Make menus easier to fully access
  gui/pause/options/options_menu.gd
  gui/pause/options/options_menu.tscn
  gui/pause/pause_menu.tscn
  scenes/menus/feedback/cancel.gd
Labels: enhancement

#82 Update handling of FLUDD visuals
  classes/global/singleton/inter_scene_data.gd
  classes/global/singleton/singleton.gd
  classes/player/fludd_sprite.gd
  classes/player/player.gd
  classes/player/player.tscn
  classes/zone/safety_net/safety_net.gd
Labels: bug, enhancement

#83 Add missing theming on OptionBoxes
  gui/scroll_v_handle_press.png
  gui/scroll_v_handle_press.png.import
  gui/theme_gui.tres
Labels: enhancement, graphics

#84 Bob-omb red flash
  classes/entity/enemy/bobomb/bobomb.gd
  classes/entity/enemy/bobomb/bobomb.tscn
Labels: enhancement

#88 Align hover spray to nozzle
  classes/player/player.gd
Labels: bug

#98 Life meter updates
  gui/life_meter/coin_charge.gd
  gui/life_meter/life_meter.gd
  gui/life_meter/life_meter.png
  gui/life_meter/life_meter.tscn
  gui/life_meter/life_meter_filler.png
  gui/life_meter/meter_life_base.png
  gui/life_meter/power_indicator.png
  gui/life_meter/power_indicator.png.import
Labels: enhancement, graphics

#107 Fix position of player's feet during dive state
  classes/player/player.gd
  classes/player/player.tscn
Labels: bug

#106 Allow Show Timer button to be bound
  classes/global/singleton/singleton.gd
  gui/timer/timer.gd
  project.godot
Labels: enhancement

#117 New terrain sheets
  classes/decorative/fossil/fossils.png
  classes/solid/terrain/tilesets/jungle/jungle_normal_spritesheet.png
Labels: graphics

#99 Improve touch buttons
  classes/global/touch_control/touch_button.gd
  classes/global/touch_control/touch_controls.gd
  gui/hud/touch_buttons.png
Labels: enhancement, graphics
