Repository GTcreyon/SM63Redux, pull requests merged in 2023-08, with the labels that each got.

#211 Fix missing text outline
  gui/theme_gui.tres
Labels: bug, graphics, godot-4-1

#213 Fix terrain memory leak
  classes/solid/terrain/terrain_border.gd
Labels: bug

#214 Screen Scaling Fixes
  classes/global/singleton/singleton.gd
  classes/player/player.tscn
  gui/hud/hud.gd
  gui/pause/level_info/level_info.tscn
Labels: bug, godot-4-1

#209 Fix feedback image
  scenes/menus/feedback/feedback.gd
Labels: bug, godot-4-1

#210 Fix alignment of text on the feedback menu
  scenes/menus/feedback/feedback.tscn
Labels: bug, godot-4-1

#219 Update Toad.gd to allow for easier editing
  classes/interactable/npc/toad/toad.gd
  classes/interactable/npc/toad/toad.tscn
Labels: enhancement

#223 Fix enemy hitbox priorities
  classes/entity/enemy/entity_enemy.gd
  classes/entity/enemy/koopa/parakoopa.gd
  classes/entity/enemy/koopa/parakoopa.tscn
  classes/entity/entity.gd
Labels: bug

#226 Fix main menu texture repeats
  scenes/menus/title/main_menu/main_menu.tscn
Labels: bug, graphics, godot-4-1

#221 Fix editor errors caused by toolscripts
  classes/interactable/interactable_dialog.gd
  classes/zone/camera_area/camera_area.gd
  classes/zone/trigger/warpzone/warp_zone.gd
Labels: godot-4-1

#222 Fix life hud flashing
  gui/life_meter/life_meter.tscn
Labels: bug, graphics
