Repository GTcreyon/SM63Redux, pull requests merged in 2023-09, with the labels that each got.

#232 Fix text outlines
  gui/theme_gui.tres
Labels: graphics, godot-4-1

#220 Fix non-integer-division code warnings
  classes/console/console.gd
  classes/entity/enemy/koopa/koopa.gd
  classes/entity/enemy/koopa/koopa_shell.gd
  classes/entity/passive/goonie/goonie.gd
  classes/global/singleton/singleton.gd
  classes/player/character_sprite.gd
  classes/player/player.gd
  classes/solid/telescoping/tipping_log/tipping_log.gd
  classes/solid/terrain/terrain_border.gd
  classes/water/water_viewport.gd
  gui/pause/buttons/pause_button.gd
  scenes/levels/tutorial_1/bg/clouds_upper.gd
  scenes/levels/tutorial_1/bg/hills.gd
  scenes/menus/title/main_menu/main_menu.gd
  scenes/menus/title/start_text.gd
Labels: godot-4-1

#243 Fix water meter bubbles scaling with window
  gui/water_meter/water_meter.gd
  gui/water_meter/water_meter.tscn
Labels: bug, graphics, godot-4-1

#227 Increase sign glow size (and other changes that need discussion)
  classes/interactable/sign/sign.gd
  classes/interactable/sign/sign.tres
  classes/interactable/sign/sign.tscn
  scenes/levels/tutorial_1/tutorial_1_1.tscn
  scenes/levels/tutorial_1/tutorial_1_2.tscn
  scenes/levels/tutorial_1/tutorial_1_3.tscn
  scenes/levels/tutorial_1/tutorial_1_4.tscn
Labels: bug, help wanted, graphics, godot-4-1

#236 Fix tiny FLUDD spray
  classes/player/player.tscn
  shaders/distance_field.gdshader
  shaders/distance_field.tres
Labels: bug, godot-4-1

#235 Make pipes usable again
  classes/interactable/pipe/pipe.tscn
Labels: bug, godot-4-1

#189 Feature command autocompletion
  classes/console/console.gd
  classes/console/console.tscn
  classes/console/console_input_line.gd
Labels: enhancement

#253 Fix some text issues
  fonts/bylight/bylight.tres
  fonts/sunbeam/sunbeam.tres
  gui/theme_gui.tres
  scenes/menus/title/start_text.gd
  scenes/menus/title/title.tscn
  scenes/menus/visual_pipescript/visual_editor_theme.tres
Labels: bug, graphics, godot-4-1

#250 Fix FLUDD bubbles cutting off
  classes/player/fludd_spray_renderer.gd
Labels: bug, graphics, godot-4-1

#249 Fix tipping log jitter
  classes/solid/telescoping/tipping_log/tipping_log.gd
Labels: bug, godot-4-1

#241 Fix ground pounding moving platforms
  classes/player/player.gd
Labels: graphics

#254 Fix leftover references to bylight.tres
  gui/hud/level_info.gd
  scenes/menus/level_designer/ldui/themes/ld_theme.tres
  scenes/menus/visual_pipescript/node.gd
  scenes/menus/visual_pipescript/node_placer.gd
Labels: bug, godot-4-1

#247 Apply pound windup animation to actual player position
  classes/player/character_sprite.gd
  classes/player/player.gd
Labels: bug, graphics

#262 Fix water meter bubbles not moving with meter
  gui/water_meter/water_meter.gd
  gui/water_meter/water_meter.tscn
Labels: bug, graphics, godot-4-1

#257 Fix palette material UIDs regenerating
  classes/entity/enemy/koopa/parakoopa.gd
  classes/interactable/npc/toad/toad.gd
  scenes/levels/tutorial_1/tutorial_1_3.tscn
  scenes/levels/tutorial_1/tutorial_1_4.tscn
  shaders/palette.tres
Labels: bug, refactor, godot-4-1

#266 Fix flying koopas are broken
  classes/entity/enemy/koopa/koopa.tscn
  classes/entity/enemy/koopa/parakoopa.gd
Labels: bug, godot-4-1

#256 Disable some toolscripts
  classes/entity/enemy/koopa/parakoopa.gd
  classes/entity/enemy/thwomp/thwomp.gd
  classes/interactable/door/door_skin.gd
  classes/interactable/interactable_dialog.gd
  classes/interactable/npc/toad/toad.gd
  classes/solid/moving_platform/pivot.gd
  classes/solid/telescoping/telescoping.gd
  classes/solid/telescoping/tipping_log/tipping_log.gd
  classes/zone/trigger/warpzone/warp_zone.gd
Labels: refactor
