Repository GTcreyon/SM63Redux, pull requests merged in 2023-10, with the labels that each got.

#261 Fix back button scaling
  gui/pause/options/touch_menu.tscn
  gui/pause/pause_menu.tscn
  gui/pause/unpause.gd
  scenes/menus/title/main_menu/main_menu.tscn
Labels: bug, graphics

#279 Enable translation
  project.godot
Labels: bug, good first issue

#281 Fix malformed color code in Portuguese translation
  locale/translations/pt_BR.po
Labels: bug, translations

#267 Un-ignore export_presets.cfg
  .gitignore
  export_presets.cfg
Labels: enhancement, help wanted
