Repository GTcreyon/SM63Redux, pull requests merged in 2023-04, with the labels that each got.

#97 Add exit menu to pause screen
  classes/console/console.gd
  classes/global/singleton/singleton.gd
  classes/global/singleton/window_warp.gd
  gui/pause/buttons/exit_buttons/pipe_button.png
  gui/pause/buttons/exit_buttons/pipe_button.png.import
  gui/pause/buttons/exit_buttons/pipe_button.tres
  gui/pause/buttons/exit_buttons/pipe_button_disabled_bright.tres
  gui/pause/buttons/exit_buttons/pipe_button_disabled_dark.tres
  gui/pause/buttons/exit_buttons/pipe_button_twosided.png
  gui/pause/buttons/exit_buttons/pipe_button_twosided.png.import
  gui/pause/buttons/exit_buttons/pipe_button_twosided.tres
  gui/pause/buttons/exit_buttons/pipe_button_twosided_disabled_bright.tres
  gui/pause/buttons/exit_buttons/pipe_button_twosided_disabled_dark.tres
  gui/pause/exit/exit.tscn
  gui/pause/exit/exit_menu.gd
  gui/pause/pause_menu.tscn
  project.godot
Labels: enhancement

#121 Add continuous collision detection to enemies
  classes/entity/enemy/cheep_cheep/cheep_cheep.gd
  classes/entity/enemy/entity_enemy.gd
Labels: bug

#124 Fix Paratroopa memory leak
  classes/entity/enemy/koopa/parakoopa.gd
Labels: bug

#135 New player sprites and animations
  classes/autoplay.gd
  classes/console/console.gd
  classes/global/singleton/inter_scene_data.gd
  classes/interactable/door/door.gd
  classes/interactable/interactable_dialog.gd
  classes/interactable/pipe/pipe.gd
  classes/interactable/sign/sign.gd
  classes/interactable/sign/sign.tscn
  classes/pickup/fludd_box/fludd_pickup.gd
  classes/player/character_sprite.gd
  classes/player/fludd_sprite.gd
  classes/player/mario_sheet.png
  classes/player/player.gd
  classes/player/player.tscn
  classes/solid/rotating_block/rotating_block.gd
  project.godot
Labels: enhancement, refactor, graphics

#138 Enhance menu graphics
  fonts/bylight/bylight.tres
  gui/boxes/menu_box.png
  gui/boxes/menu_box.png.import
  gui/boxes/menu_box_drop.tres
  gui/boxes/menu_box_hover.tres
  gui/boxes/menu_box_normal.tres
  gui/boxes/menu_box_pressed.tres
  gui/dropdown_arrow.png
  gui/dropdown_arrow.png.import
  gui/pause/options/layout_select.gd
  gui/pause/options/locale_select.gd
  gui/pause/options/options_menu.tscn
  gui/pause/options/touch_menu.tscn
  gui/radio.png
  gui/radio.png.import
  gui/theme_gui.tres
  project.godot
  scenes/menus/title/logo/logo.png
  scenes/menus/title/logo/sparkles.png
  scenes/menus/title/main_menu/crystal.png
  scenes/menus/title/main_menu/hook.png
  scenes/menus/title/main_menu/main_menu.gd
  scenes/menus/title/main_menu/main_menu.tscn
  scenes/menus/title/main_menu/menu_orb.png
  scenes/menus/title/main_menu/menu_orb.png.import
  scenes/menus/title/main_menu/menu_titles.png
  scenes/menus/title/main_menu/orb_inner.png
  scenes/menus/title/main_menu/orb_inner.png.import
  scenes/menus/title/main_menu/preview_orb.gd
  scenes/menus/title/main_menu/selection_content.png
  scenes/menus/title/main_menu/selection_frame.png
  scenes/menus/title/main_menu/selector.png
Labels: enhancement, graphics

#139 Enhance HUD sprites
  fonts/red/gui_red.png
  fonts/white/gui_white.png
  gui/hud/hud.tscn
  gui/hud/hud_coin.png
  gui/hud/hud_coin.png.import
  gui/hud/hud_icons.png
  gui/hud/hud_icons.png.import
  gui/hud/hud_red_coin.png
  gui/hud/hud_red_coin.png.import
  gui/hud/hud_shine.png
  gui/hud/hud_shine.png.import
  gui/hud/hud_shine_coin.png
  gui/hud/hud_shine_coin.png.import
  gui/hud/hud_shine_small.png
  gui/hud/hud_shine_small.png.import
  gui/hud/hud_silver_shine.png
  gui/hud/hud_x.png
  gui/hud/hud_x.png.import
  gui/pause/map/map.tscn
  project.godot
Labels: enhancement, graphics

#133 Upgrade ResidualSFX.new_from_existing error handling
  classes/misc/residual_sfx/residual_sfx.gd
Labels: refactor

#137 Fix Koopas spawning multiple shells when being struck
  classes/entity/enemy/koopa/koopa.gd
Labels: bug

#146 Layer FLUDD box behind the player
  classes/pickup/fludd_box/fludd_box.tscn
Labels: enhancement, graphics

#147 Fix dialogue box portrait not showing up
  gui/dialog/dialog_box.gd
  gui/dialog/dialog_box.tscn
Labels: bug

#150 Remove desaturation shader from Extras arrow
  scenes/menus/title/main_menu/main_menu.tscn
Labels: enhancement, graphics

#144 Fix broken animation when buffering a jump
  classes/player/character_sprite.gd
  classes/player/player.gd
Labels: bug

#145 Add manual polygon edge type setting
  classes/solid/terrain/pencil.gd
  classes/solid/terrain/terrain_polygon.gd
  scenes/levels/tutorial_1/tutorial_1_1.tscn
Labels: enhancement, graphics

#152 Fix broken quote blocks in feedback menu
  scenes/menus/feedback/feedback.gd
Labels: bug

#153 Append a hash to feedback reports
  scenes/menus/feedback/feedback.gd
Labels: documentation, enhancement

#167 Fix bus of ResidualSFX
  classes/misc/residual_sfx/residual_sfx.gd
Labels: bug

#165 Fix jumping during coyote time playing fall anim
  classes/player/character_sprite.gd
  classes/player/player.gd
Labels: bug

#162 Make underwater SFX respect player's mute settings
  classes/entity/enemy/cheep_cheep/cheep_cheep.tscn
  classes/player/player.tscn
  default_bus_layout.tres
  gui/pause/options/options_menu.gd
Labels: bug, refactor

#166 Fix nozzle pickups layering in front of boxes
  classes/pickup/fludd_box/fludd_pickup_hover.tscn
  classes/pickup/fludd_box/fludd_pickup_rocket.tscn
  classes/pickup/fludd_box/fludd_pickup_turbo.tscn
Labels: bug

#163 Fix underwater terrain edges
  scenes/levels/tutorial_1/tutorial_1_2.tscn
  scenes/levels/tutorial_1/tutorial_1_3.tscn
Labels: bug, graphics

#164 Fix animation not being set properly when reading signs
  classes/interactable/interactable_dialog.gd
  classes/player/character_sprite.gd
  gui/dialog/dialog_box.gd
Labels: bug

#170 Change speed of initial dive animation
  classes/player/player.tscn
Labels: graphics
