Repository GTcreyon/SM63Redux, pull requests merged in 2023-02, with the labels that each got.

#65 Fix multiple-player FLUDD spray
  classes/player/bubbles.gd
  classes/player/fludd_spray.shader
  classes/player/fludd_spray.tres
  classes/player/fludd_spray_renderer.gd
  classes/player/player.gd
  classes/player/player.tscn
  gui/hud/hud.gd
Labels: bug, refactor

#66 Enhance triple jump anim
  classes/player/player.gd
Labels: enhancement, refactor

#69 Make "underwater effect" bypassable
  classes/player/player.gd
  default_bus_layout.tres
Labels: refactor, audio

#74 Fix fludd meter not being visible
  gui/hud/hud.tscn
Labels: bug

#76 Fix FLUDD nozzles not respawning
  classes/pickup/fludd_box/fludd_pickup_hover.tscn
  classes/pickup/fludd_box/fludd_pickup_rocket.tscn
  classes/pickup/fludd_box/fludd_pickup_turbo.tscn
Labels: bug
