Repository GTcreyon/SM63Redux, pull requests merged in 2023-01, with the labels that each got.

#44 Quieter FLUDD box
  classes/pickup/fludd_box/fludd_box.tscn
Labels: enhancement, audio

#46 Player Sound Effects
  classes/player/hover.mp3.import
  classes/player/hover_loop.mp3.import
  classes/player/player.gd
  classes/player/player.tscn
  classes/player/sfx/fludd/fludd_switch.wav
  classes/player/sfx/fludd/fludd_switch.wav.import
  classes/player/sfx/fludd/hover.mp3
  classes/player/sfx/fludd/hover.mp3.import
  classes/player/sfx/fludd/hover_loop.mp3
  classes/player/sfx/fludd/hover_loop.mp3.import
  classes/player/sfx/pound/pound_cloud.wav
  classes/player/sfx/pound/pound_cloud.wav.import
  classes/player/sfx/pound/pound_generic.wav
  classes/player/sfx/pound/pound_generic.wav.import
  classes/player/sfx/pound/pound_grass.wav
  classes/player/sfx/pound/pound_grass.wav.import
  classes/player/sfx/pound/pound_sand.wav
  classes/player/sfx/pound/pound_sand.wav.import
  classes/player/sfx/pound/pound_snow.wav
  classes/player/sfx/pound/pound_snow.wav.import
  classes/player/sfx/pound/pound_spin.wav
  classes/player/sfx/pound/pound_spin.wav.import
  classes/player/sfx/spin_air_1.wav
  classes/player/sfx/spin_air_1.wav.import
  classes/player/sfx/spin_air_2.wav
  classes/player/sfx/spin_air_2.wav.import
  classes/player/sfx/spin_air_3.wav
  classes/player/sfx/spin_air_3.wav.import
Labels: enhancement, refactor, audio

#50 Trim single jump sounds
  classes/player/sfx/mario/jump_single/jump_single_0.wav
  classes/player/sfx/mario/jump_single/jump_single_1.wav
Labels: enhancement, audio

#45 Bob-omb sound effects
  classes/entity/enemy/bobomb/bobomb.gd
  classes/entity/enemy/bobomb/bobomb.tscn
  classes/entity/enemy/bobomb/explosion.wav
  classes/entity/enemy/bobomb/explosion_buildup_1.wav
  classes/entity/enemy/bobomb/explosion_buildup_1.wav.import
  classes/entity/enemy/bobomb/explosion_buildup_2.wav
  classes/entity/enemy/bobomb/explosion_buildup_2.wav.import
  classes/entity/enemy/bobomb/fuse.wav
  classes/entity/enemy/bobomb/fuse.wav.import
  classes/entity/enemy/bobomb/knock.wav
  classes/entity/enemy/bobomb/knock.wav.import
Labels: enhancement, audio

#47 Heftier ground pound feedback
  classes/dejitter_group/dejitter_group.gd
  classes/player/mario_sheet.png
  classes/player/player.gd
  classes/player/player.tscn
Labels: enhancement

#51 Fixes to menus and UI
  classes/global/singleton/singleton.gd
  classes/global/touch_control/touch_button.gd
  classes/global/touch_control/touch_controls.gd
  classes/interactable/interactable_dialog.gd
  classes/misc/containers/scale_container.gd
  classes/player/camera.gd
  classes/player/player.tscn
  gui/hud/hud.gd
  gui/hud/hud.tscn
  gui/hud/level_info.gd
  gui/hud/pause_content.gd
  gui/hud/shine_map.gd
  gui/life_meter/life_meter.gd
  gui/life_meter/life_meter.tscn
  gui/pause/buttons/pause_button.gd
  gui/pause/level_info/level_info.tscn
  gui/pause/map/map.tscn
  gui/pause/options/options_menu.gd
  gui/pause/options/options_menu.tscn
  gui/pause/options/rebind_option.gd
  gui/pause/pause.tscn
  gui/pause/pause_back.tres
  gui/pause/pause_menu.tscn
  scenes/levels/tutorial_1/bg/clouds_lower.gd
  scenes/levels/tutorial_1/bg/clouds_upper.gd
  scenes/levels/tutorial_1/bg/hills.gd
  scenes/menus/feedback/cancel.gd
  scenes/menus/feedback/feedback.gd
  scenes/menus/feedback/feedback.tscn
  scenes/menus/title/main_menu/main_menu.gd
  scenes/menus/title/main_menu/main_menu.tscn
  scenes/menus/title/sheen.gd
  scenes/menus/title/title.tscn
  shaders/glow.shader
  shaders/glow.tres
Labels: bug, enhancement, refactor, graphics

#54 Customizable lifetime for falling logs
  classes/solid/log/log_fall.gd
Labels: bug, enhancement

#57 Warp command refactor
  classes/console/console.gd
Labels: refactor
